/**
 * dynamic-wkhtmltopdf
 *
 *
 * Copyright (c) 2020 Navjot Dhanawat
 * Licensed under the MIT license.
 */

/**
 * Dynamic handlebars pdf is used to create pdf from handlebar templates.
 * @param  {document, options}
 * @return {callback}
 */

var Handlebars = require("handlebars"),
  wkhtmltopdf = require("wkhtmltopdf");

// Handlebar helper support
module.exports.registerHelper = (conditionName, callback) => {
  Handlebars.registerHelper(conditionName, callback);
};

module.exports.create = (document, options) => {
  // Compile handlebar template
  return new Promise((resolve, reject) => {
    if (!document || !document.template || !document.context) {
      reject(new Error("Some, or all, options are missing."));
    }

    if (document.type !== "buffer" && !document.path) {
      reject(
        new Error(
          "Please provide path parameter : stream || buffer || file(default)"
        )
      );
    }

    var html = Handlebars.compile(document.template)(document.context);

    if (document.type === "buffer") {
      // Create PDF from html template generated by handlebars
      //Output will be buffer
      wkhtmltopdf(html, options, (err, stream) => {
        if (!err) resolve(stream.read());
        else reject(err);
      });
    } else if (document.type === "stream") {
      // Create PDF from html template generated by handlebars
      // Output will be Stream
      wkhtmltopdf(html, options, (err, stream) => {
        if (!err) resolve(stream);
        else reject(err);
      });
    } else {
      // Create PDF from html template generated by handlebars
      // Output will be PDF file
      wkhtmltopdf(html, { output: document.path, ...options }, (err, res) => {
        if (!err) resolve(res);
        else reject(err);
      });
    }
  });
};